export const items = [
    {
        id:1,
        imageURL:"https://growdice.co/assets/50__profit-5d4d541e.png?format=webp",
        title:"LUCKY",
        price:0.88
    },
    {
        id:2,
        imageURL:"https://growdice.co/assets/10__phoenix-e982e152.png?format=webp",
        title:"STARTER",
        price:0.61
    },
    {
        id:3,
        imageURL:"https://growdice.co/assets/exotic_accessories-c0dd0323.png?format=webp",
        title:"ALL IN",
        price:0.35
    },
    {
        id:4,
        imageURL:"https://growdice.co/assets/booster-6d1c3351.png?format=webp",
        title:"BOOSTER",
        price:0.27
    },
    {
        id:5,
        imageURL:"https://growdice.co/assets/10__scythe-08b601fa.png?format=webp",
        title:"CHAOS",
        price:0.11
    },
    {
        id:6,
        imageURL:"https://growdice.co/assets/treasure-e8e879d5.png?format=webp",
        title:"FIRE",
        price:0.10
    },
    
    {
        id:7,
        imageURL:"https://growdice.co/assets/50__profit-5d4d541e.png?format=webp",
        title:"50% PROFIT",
        price:0.88
    },
    {
        id:8,
        imageURL:"https://growdice.co/assets/10__phoenix-e982e152.png?format=webp",
        title:"EXOTIC",
        price:1.04
    },
    {
        id:9,
        imageURL:"https://growdice.co/assets/exotic_accessories-c0dd0323.png?format=webp",
        title:"NO CARNIVAL",
        price:1.50
    },
    {
        id:10,
        imageURL:"https://growdice.co/assets/booster-6d1c3351.png?format=webp",
        title:"SPARKLING",
        price:2.51
    },
    {
        id:11,
        imageURL:"https://growdice.co/assets/10__scythe-08b601fa.png?format=webp",
        title:"10% PHOENIX",
        price:4.08
    },
    {
        id:12,
        imageURL:"https://growdice.co/assets/treasure-e8e879d5.png?format=webp",
        title:"GEMSTONE",
        price:5.00
    },
    {
        id:13,
        imageURL:"https://growdice.co/assets/starter-6b251a2b.png?format=webp",
        title:"LOW RISK",
        price:6.33
    },
    {
        id:14,
        imageURL:"https://growdice.co/assets/50__profit-5d4d541e.png?format=webp",
        title:"BALLER",
        price:299.88
    },
    {
        id:15,
        imageURL:"https://growdice.co/assets/10__phoenix-e982e152.png?format=webp",
        title:"CURSED",
        price:6.66
    },
    {
        id:16,
        imageURL:"https://growdice.co/assets/exotic_accessories-c0dd0323.png?format=webp",
        title:"FROSTY",
        price:5.13
    },
    {
        id:17,
        imageURL:"https://growdice.co/assets/booster-6d1c3351.png?format=webp",
        title:"WINTER",
        price:15.04
    },
    {
        id:18,
        imageURL:"https://growdice.co/assets/10__scythe-08b601fa.png?format=webp",
        title:"COMEBACK",
        price:14.84
    },
    {
        id:19,
        imageURL:"https://growdice.co/assets/treasure-e8e879d5.png?format=webp",
        title:"TREASURE",
        price:150.14
    },
    {
        id:20,
        imageURL:"https://growdice.co/assets/starter-6b251a2b.png?format=webp",
        title:"MAGPLANT",
        price:63.01
    },
    {
        id:21,
        imageURL:"https://growdice.co/assets/50__profit-5d4d541e.png?format=webp",
        title:"LUXURY",
        price:10.59
    },
    {
        id:22,
        imageURL:"https://growdice.co/assets/10__phoenix-e982e152.png?format=webp",
        title:"RAYMAN",
        price:191.05
    },
    {
        id:23,
        imageURL:"https://growdice.co/assets/exotic_accessories-c0dd0323.png?format=webp",
        title:"LUCKY",
        price:109.92
    },
    {
        id:24,
        imageURL:"https://growdice.co/assets/starter-6b251a2b.png?format=webp",
        title:"10% SCYT",
        price:0.87
    }
]